server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:com/huiwtech/film/**/xml/*Mapper.xml
  global-config:
    id-type: 0 #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next_film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  level.root: info
  level.com.next.jiangzh: debug
  path: logs/
  file: next-film.log